### ISSUE TITLE
how to change dataser

### ISSUE THREAD

**Issue by kobrafarshidi** [uakarsh/latr#4]
I am trying to run your project .First I start run with pre-training step by step until eighth block but in the ninth block you mention  ## There can be error, if the Image file does not exist, so I request you to make changes in the dataset object, such that those address are removed ## and I have error but I cant understand where I should change in script dataset in src folder and what is image file? I would be grateful if you guided me through this.

**Comment by uakarsh** [comment]
HI @kobrafarshidi, can you let me know the error message you get, while running the code?

**Comment by kobrafarshidi** [comment]
yes sure .

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-16-cce8031e6895>](https://localhost:8080/#) in <module>
      1 ## There can be error, if the Image file does not exist, so I request you to make changes in the dataset object, such that those address are removed
      2 
----> 3 dl_entry = next(iter(dl))
      4 masked_boxes, masked_tokenized_words, tokenized_words = dl_entry

4 frames
[<ipython-input-13-34a090736bd2>](https://localhost:8080/#) in __getitem__(self, idx)
     39                                                   use_ocr = False,
     40                                                   bounding_box = coordinates,
---> 41                                                   words = words
     42                                                   )
     43     boxes = torch.as_tensor(boxes, dtype=torch.int32)

TypeError: create_features() got an unexpected keyword argument 'image_path'














---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-16-cce8031e6895>](https://localhost:8080/#) in <module>
      1 ## There can be error, if the Image file does not exist, so I request you to make changes in the dataset object, such that those address are removed
      2 
----> 3 dl_entry = next(iter(dl))
      4 masked_boxes, masked_tokenized_words, tokenized_words = dl_entry

4 frames
[<ipython-input-13-34a090736bd2>](https://localhost:8080/#) in __getitem__(self, idx)
     39                                                   use_ocr = False,
     40                                                   bounding_box = coordinates,
---> 41                                                   words = words
     42                                                   )
     43     boxes = torch.as_tensor(boxes, dtype=torch.int32)

TypeError: create_features() got an unexpected keyword argument 'image_path'

**Comment by kobrafarshidi** [comment]
![1e](https://user-images.githubusercontent.com/91652559/191083075-89ef3b96-a152-43c4-a5ff-cd6608d7a4b7.PNG)

**Comment by uakarsh** [comment]
I think, the code should be `img, boxes, tokenized_words = create_features(img_path = tif_path,
                                                  tokenizer = self.tokenizer,
                                                  target_size = (1000, 1000),
                                                  use_ocr = False,
                                                  bounding_box = coordinates,
                                                  words = words
                                                  )`, I think, I changed the name of the parameter after releasing the example. Do, let me know, if it works or not

Regards,
Akarsh
