### ISSUE TITLE
Error in use of your dataset textvqa

### ISSUE THREAD

**Issue by kobrafarshidi** [uakarsh/latr#6]
Hi. I am trying to use your textVQA dataset that you mention in source code but I could not and that give me error. I send you that error. I'd appreciate it if you could help me with it.
your address in program was 
[https://drive.google.com/drive/folders/1bR03cRGnPENCiUaurKSGTSNQHUQlsDCR?usp=sharing]
![12](https://user-images.githubusercontent.com/91652559/191721691-e319e351-8238-40c2-b3e8-782a4b468570.PNG)

**Comment by uakarsh** [comment]
I removed it due to space issues. I guess you can download it from the official site, and then unzip it to the appropriate path and then continue.

**Comment by kobrafarshidi** [comment]
That is right.Thank you for your responce. So can I ask what is the official site address exactly? and Do I change some files and create some folder or it is just enough to download it?

    On Thursday, September 22, 2022, 10:25:08 AM EDT, uakarsh ***@***.***> wrote:  
 
 


I removed it due to space issues. I guess you can download it from the official site, and then unzip it to the appropriate path and then continue.

**Comment by uakarsh** [comment]
It is at this [link](https://textvqa.org/dataset/) . I don't think, you would need anything except for unzipping the file and changing the directory path in the code.

**Comment by kobrafarshidi** [comment]
That is right .Thank you so much.
    On Thursday, September 22, 2022, 11:25:23 AM EDT, uakarsh ***@***.***> wrote:  
 
 


It is at this link . I don't think, you would need anything except for unzipping the file and changing the directory path in the code.
